name: Build & Test
on:
  pull_request:
  push:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Build
        run: make build
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16
      - uses: actions/checkout@v2
      - name: Test
        run: go test ./... -mod=readonly -timeout 30m -coverprofile=profile.out -covermode=atomic -race
